theme: jekyll-theme-slate

markdown: kramdown

remote_theme: jekyll/minima

plugins:
  - jekyll-remote-theme

minima:
  # Minima skin selection.
  # Available skins are:
  # classic	           Default, light color scheme.
  # dark	             Dark variant of the classic skin.
  # auto	             Adaptive skin based on the default classic and dark skins.
  # solarized-light	   Light variant of solarized color scheme.
  # solarized-dark	   Dark variant of solarized color scheme.
  # solarized	         Adaptive skin for solarized color scheme skins.
  skin: solarized-dark

show_excerpts: true

header_pages:
  - test.md
  - about.md
  - practices.md
  - bragging.md
  